Fix saving background and foreground color issue
I encountered the following problem when using `Color Theme Editor`:

Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/gedit/plugins/colorschemer/schemer.py", line 569, in on_style_changed
    (color.red * cScale, color.green * cScale, color.blue * cScale))
TypeError: %x format: an integer is required, not float

I think this change will fix the problem